# Generated by Django 5.0.10 on 2024-12-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='grupopersonalizado',
            constraint=models.UniqueConstraint(fields=('name', 'empresa'), name='unique_group_name_per_empresa'),
        ),
    ]
