# Generated by Django 5.0.10 on 2024-12-09 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_grupopersonalizado_unique_group_name_per_empresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupopersonalizado',
            options={'verbose_name': 'Grupo Personalizado', 'verbose_name_plural': 'Grupos Personalizados'},
        ),
        migrations.RemoveConstraint(
            model_name='grupopersonalizado',
            name='unique_group_name_per_empresa',
        ),
    ]
