# Generated by Django 5.0.10 on 2024-12-10 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_grupopersonalizado_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupopersonalizado',
            options={},
        ),
    ]
