# Generated by Django 5.0.9 on 2024-12-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tarjetacredito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetacredito',
            name='fecha_vencimiento',
            field=models.CharField(max_length=10),
        ),
    ]
