# Generated by Django 5.0.9 on 2024-12-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_tarjetacredito_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='directorio',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='fecha_vencimiento',
            field=models.DateField(max_length=10),
        ),
    ]
